public enum MessageType {
    TEXT, NEWCONNECTION, DISCONNECTED, LOGIN, JOIN_GAME, GAME_STATE, GAME_ACTION, NEWONLINE, ALREADYONLINE, ALREADYOFFLINE, WAITING, NEWGAMESESSION, LEAVE_QUEUE, QUIT_GAME
}
