public enum MessageType {
    TEXT, NEWCONNECTION, DISCONNECTED, LOGIN, JOIN_GAME, GAME_STATE, GAME_ACTION, NEWONLINE, ALREADYONLINE, WAITING, NEWGAMESESSION, LEAVE_QUEUE, QUIT_GAME, REMATCH, REMATCH_ACCEPT, LOGOUT
}